---
title: "Fig4"
output: html_notebook
---

# Load libraries/data
```{r}
library(tidyverse)
library(Seurat)
library(cowplot)
library(ggplot2)
library(rstatix)
library(readxl)
library(progeny)

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
epi<-subset(sc,cells=which(sc$epithelial_subcluster_type=="EnEpi cells"&
                               !is.na(sc$published_epithelial_subtype)))
gc()
markers<-read_excel("../Downloads/41588_2022_1254_MOESM4_ESM.xlsx",sheet = 7,skip =2)
markers<-markers%>%filter(Cluster%in%c("SOX9+/LGR5+","Glandular secretory",
                                       "IHH+/SPDEF+","MUC5B+","Ciliated"))
```

# Label transfer
## Subcluster level
```{r}
organoids <- readRDS("data/MONT0013_PostQC_PostCluster_Plates1-8.rds")
#computation intenstive - run of memory once
epi_anchors <- FindTransferAnchors(reference = epi,
                                   query = organoids,
                                   normalization.method = 'SCT',
                                   features = unique(markers$Gene))
predictions <- TransferData(anchorset = epi_anchors,
                            refdata = epi$published_epithelial_subtype)

#rganoids <- IntegrateEmbeddings(anchorset = epi_anchors, reference = epi,
# query = organoids, new.reduction.name = "ref.pca")
#organoids <- ProjectUMAP(query = organoids, query.reduction = "ref.pca", reference = epi,
# reference.reduction = "pca", reduction.model = "umap")

organoids <- AddMetaData(organoids,metadata = predictions)
#p1 <- DimPlot(epi, reduction = "umap", group.by = "published_epithelial_subtype", label = TRUE, label.size = 3,
#              repel = TRUE) + NoLegend() + ggtitle("Reference annotations")
#p2 <- DimPlot(organoids, reduction = "ref.umap", group.by = "predicted.id",label = TRUE,
#              label.size = 3, repel = TRUE) + NoLegend() + ggtitle("Query transferred labels")
#png("label_transfer.UMAP.png")
#p1 + p2
#dev.off()

saveRDS(organoids,"data/MONT0013_PostQC_PostCluster_Plates1-8.rds")

```

## Cluster level 
```{r}
endo_anchors <- FindTransferAnchors(reference = sc,query = organoids,normalization.method = 'SCT')
predictions <- TransferData(anchorset = endo_anchors,refdata = sc$harmonized_major_cell_type)
colnames(predictions)[c(1,16)]<-paste0("harmon_",colnames(predictions)[c(1,16)])

organoids <- AddMetaData(organoids,metadata = predictions)
saveRDS(organoids,"data/MONT0013_PostQC_PostCluster_Plates1-8.rds")

```

# sanity check 
```{r}
FeaturePlot(organoids,features = c("prediction.score.IHH..SPDEF.",
                                   "prediction.score.Glandular.secretory",
                                   "prediction.score.MUC5B.",
                                   "prediction.score.SOX9..LGR5.",
                                   "prediction.score.Ciliated",
                                   "prediction.score.EnEpi.cells",
                                   "prediction.score.EnS.cells"))
Idents(organoids)<-organoids$seurat_clusters
VlnPlot(organoids,features = c("prediction.score.IHH..SPDEF.",
                               "prediction.score.Glandular.secretory", 
                               "prediction.score.MUC5B.", 
                               "prediction.score.SOX9..LGR5.", 
                               "prediction.score.Ciliated", 
                               "prediction.score.EnEpi.cells",
                               "prediction.score.EnS.cells"),pt.size = 0)

organoids@meta.data%>%
  group_by(predicted.id)%>%
  summarise(score=mean(prediction.score.max),n=n())
```
# new annotations considering cluster and subcluster prediction
```{r}
organoids@meta.data<-organoids@meta.data%>%
  mutate(final_prediction=ifelse(harmon_predicted.id=="EnEpi cells",
                                 predicted.id,
                                 harmon_predicted.id))
organoids@meta.data<-organoids@meta.data%>%
  mutate(final_prediction=ifelse(prediction.score.max<.5&harmon_prediction.score.max<.5,
                                 "unclassified",
                                 final_prediction))
```

# Add scores
```{r}
il1<-read_tsv("docs/IL1_signaling_hormone_targets.tsv")
organoids<-AddModuleScore(organoids,features = list(unique(il1$gene_symbol)),
                          name = "signaling_IL",assay = "RNA")

organoids <- progeny(organoids, scale=FALSE, organism="Human",
                     top=100,return_assay = TRUE)#perm>1 is slow but produces pvalues
organoids <- Seurat::ScaleData(organoids, assay = "progeny")
temp<-t(organoids@assays$progeny@scale.data)
organoids<-AddMetaData(organoids,temp)

```

# Filter EnEpi subclusters
```{r}
org1<-subset(organoids,
             cells=which(str_detect(organoids$final_prediction,"SOX9|MUC|dular|IHH|ated")))

sanity_markers<-list("SOX9+LGR5+"=c("SOX9","LGR5","MMP7","ESR1","PGR"),
                "MUC5+"=c("MUC5B", "TFF3"), 
                "Glandular\nsecretory"=c("PAEP", "DPP4", "SPP1"), 
                "IHH+SPDEF+"=c("IHH","SPDEF","SERPINA5","HIF1A"),
                 Ciliated=c("TPPP3", "PIFO", "FOXJ1"))
sanity_markers<-sanity_markers%>%reshape2::melt()%>%
  mutate(marker=value)%>%select(-value)%>%deframe()

temp<-org1@meta.data%>%count(final_prediction)%>%arrange(n)%>%
  mutate(final_prediction=factor(final_prediction,levels=final_prediction))
Idents(org1)<-factor(org1$final_prediction,levels=temp$final_prediction)
sc2A<-DotPlot(org1,features = sanity_markers)+RotatedAxis()+
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme(strip.text = element_text(angle=80))+
  labs(x="Gene",y="")+
  guides(color = guide_colorbar(title = "Average\nexpression"),
           size=guide_legend(title="Percent\nexpressed"))
sc2B<-temp%>%
  ggplot(aes(x=n,y=final_prediction))+geom_col()+
  theme_classic(base_size = 14)+labs(y="")+
  theme(axis.text.y = element_blank(),axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
        axis.title.y = element_blank())+
  scale_x_continuous(trans = "log10")
sc2C<-org1@meta.data%>%
  mutate(final_prediction=factor(final_prediction,levels=temp$final_prediction))%>%
  ggplot(aes(x=prediction.score.max,y=final_prediction))+
  geom_boxplot()+
  theme_classic(base_size = 14)+labs(y="")+
  theme(axis.text.y = element_blank(),axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
        axis.title.y = element_blank())
sc2<-plot_grid(sc2A+theme(legend.position = "none"),
               sc2C,sc2B,ncol=3,align = 'h',axis = 'bt',rel_widths = c(.5,.2,.2))
sc2<-plot_grid(sc2,get_legend(sc2A),rel_widths = c(.9,.1))
ggsave(filename = "supp2.pdf",device = cai)
```

# Sanity plots show an overlap between clusters: separate Ciliated vs non-ciliated
```{r}
org1@meta.data<-org1@meta.data%>%
  mutate(simplified_prediction=ifelse(final_prediction=="Ciliated",
                                      final_prediction,
                                      "Non-ciliated"))

Idents(org1)<-factor(org1$simplified_prediction,levels = c("Non-ciliated","Ciliated"))
sf1<-DimPlot(org1,cols = c("gray","#d53e48"),label.size = 4,alpha=0.4,label = T,repel=T)+
    NoLegend()+NoAxes()+xlim(-9,6)+
    annotate("segment", 
             x = c(-7,-7), xend = c(-3,-7), 
             y = c(-7,-7), yend = c(-7,-1), 
             arrow = arrow(type = "closed", length = unit(10, 'pt')))+
    annotate("text",x = -5.5,y=-8.5,label="UMAP 1",size=4)+
    annotate("text",x=-8,y=-5,label="UMAP 2",size=4,angle=90)+
  theme(axis.text = element_text(angle=14))

sf2<-org1@meta.data%>%
  ggplot(aes(x=simplified_prediction,
             y=signaling_IL1))+
  geom_violin(aes(fill=simplified_prediction),show.legend = F)+
  stat_compare_means(method = "t.test",label = "p.signif")+
  theme_classic(base_size = 14)+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
  labs(x="",y="IL1 signaling")+
  scale_fill_manual(values = c("gray","#d53e48"))

sf3<-DotPlot(org1,features = c("IL1A","IL1B","IL1R1","IL1R2","IL1RAP","MYD88","IRAK1","IRAK4","TRAF6","IKBKB","IKBKG","NFKB1","NFKB2"))+
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+coord_flip()+labs(y="Gene",x="")+
  theme_classic(base_size = 14)+theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
    guides(color = guide_colorbar(title = "Average\nexpression"),
           size=guide_legend(title="Percent\nexpressed"))

temp<-org1@assays$progeny$scale.data%>%t()%>%
  as.data.frame%>%
  rownames_to_column("barcode")%>%
  inner_join(org1@meta.data%>%select(barcode,simplified_prediction,signaling_IL1),
             by="barcode")
temp<-temp%>%pivot_longer(cols = Androgen:WNT,
                          names_to = "pathway",
                          values_to = "progeny_score")%>%drop_na()
temp<-temp%>%group_by(pathway)%>%mutate(box=cut(progeny_score,breaks=10,labels=F))%>%ungroup
temp<-temp%>%group_by(pathway,box,simplified_prediction)%>%
summarise(activity=median(progeny_score),avg_IL1=mean(signaling_IL1),size=n())%>%
ungroup()%>%distinct()%>%mutate(pathway=str_replace(pathway,"NFkB","NFκB")%>%
         str_replace("TGFb","TGFβ")%>%
         str_replace("TNFa","TNFα"))

#temp%>%
#    ggplot(aes(x=activity,y=avg_IL1,group=simplified_prediction,color=simplified_prediction))+
#    geom_point(aes(size=size))+geom_line()+facet_wrap(~pathway,scales="free",nrow = 3)+
#    theme_classic(base_size=16)+labs(color="Cell type",size="Cells",y="Average IL1")+
#    theme(strip.background=element_blank(),
#          legend.position = "bottom",legend.box = "vertical")+
#    scale_color_manual(values=c("#d53e48","gray"))+
#    guides(col=guide_legend(nrow=2))
sf4<-temp%>%filter(pathway=="Estrogen")%>%
    ggplot(aes(x=box,y=avg_IL1,group=simplified_prediction,color=simplified_prediction))+
    geom_point(aes(size=size))+geom_line()+
    theme_classic(base_size=14)+labs(color="Cell type",size="Cells",y="Average IL1\nsignaling",x="Estrogen")+
    theme(legend.position = "bottom",legend.box = "vertical")+
    scale_color_manual(values=c("#d53e48","gray"))#+
#  stat_cor(method = "spearman")

ggsave("m_fig4.pdf",plot = plot_grid(plot_grid(NULL,sf1,NULL,nrow=3,rel_heights = c(.1,.8,.1)),sf2,sf3+theme(legend.position = "none"),get_legend(sf3),sf4,ncol=5,labels = c('a','b','c','','d'),rel_widths = c(.2,.15,.2,.1,.35)),height = 4,width = 13,device = cairo_pdf)

```
