---
title: "scDRS DotPlot"
---

```{r}
library(tidyverse)
library(Seurat)
library(cowplot)
library(ggplot2)

aux_table<-data.table::fread("data/fixed_annotated_aux.seurat.metadata.tsv")
aux_table<-aux_table%>%filter(!harmonized_major_cell_type%in%c("Exclude","Erythrocytes"))

aux_table<-aux_table%>%
  mutate(group_major_plus_immune=str_replace(harmonized_major_plus_immune_cell_type,"Memmory","Memory")%>%
           str_replace("Gamma-Delta","γδ")%>%
           str_replace("Cells","cells")%>%
           str_remove(" \\(.+"))

cell_order<-aux_table%>%distinct(harmonized_major_cell_type)%>%
  mutate(type=ifelse(str_detect(harmonized_major_cell_type,"B|Mast|Myel|NK|Plas|T"),
                     "immune","non"))%>%
  arrange(type,harmonized_major_cell_type)
cell_order<-cell_order[c(1,5,2:4,6:nrow(cell_order)),]
cell_order1<-aux_table%>%
  filter(!is.na(aux_table$Final_Immune_Cluster_ID))%>%
  mutate(harmonized_major_cell_type=ifelse(str_detect(group_major_plus_immune,"Early"),
                                           "T cells",
                                           harmonized_major_cell_type))%>%
  count(harmonized_major_cell_type,group_major_plus_immune)
cell_order1<-cell_order1[c(1,7,2:6,8,11,9,10,12:15),]

```

# Format scores table 
```{r}
files<-list.files("/media/msoledad/07B3-2CF8/scDRS",full.names = T)
files<-files[str_detect(files,"\\.score.gz")]
files<-files[-2]#drop merged file, check manually

scdrs<-lapply(files,read_tsv)
names(scdrs)<-str_remove_all(files,".+scDRS/|.score.gz")
scdrs<-lapply(names(scdrs),function(x) scdrs[[x]]%>%mutate(trait=x))%>%bind_rows()
colnames(scdrs)[1]<-"barcode"
scdrs<-aux_table%>%
  select(group_major_plus_immune,barcode,Class,Stage.y)%>%
  left_join(scdrs,by="barcode")

plot_df<-scdrs%>%
  drop_na()%>%filter(trait!="endometriosis")%>%
  group_by(trait,group_major_plus_immune)%>%
  summarise(total=n(),
            signi=sum(mc_pval<0.05),
            prop=100*signi/total,
            score=mean(norm_score))
```

# Add group significance 
```{r}
files<-list.files("/media/msoledad/07B3-2CF8/scDRS",full.names = T)
files<-files[str_detect(files,"group_harmonized")]
group<-lapply(files, read_tsv)
names(group)<-str_remove_all(files,".+scDRS/|.scdrs_group.group_harmonized_major_plus_immune")
group<-lapply(names(group),function(x) 
  group[[x]]%>%mutate(trait=x))%>%bind_rows()
group<-group%>%
  mutate(group=str_replace(group,"Memmory","Memory")%>%
           str_replace("Gamma-Delta","γδ")%>%
           str_replace("Cells","cells")%>%
           str_remove(" \\(.+"))

colnames(plot_df)[2]<-"group"
plot_df<-plot_df%>%merge(group,by=c("trait","group"))

plot_df$trait=str_replace_all(plot_df$trait,'_',' ')%>%
           str_replace("hg","high grade serous ovarian cancer")%>%
           str_replace("clearcell","clear cell ovarian cancer")%>%
           str_replace("endometroid","endometroid ovarian cancer")%>%
           str_replace("abdo pelvic","abdominal and pelvic")
plot_df<-plot_df%>%mutate(group=str_replace(group," Memo"," memo")%>%
                            str_replace("ly Exh","ly exh"),
                          trait=str_to_sentence(trait)%>%str_replace("Ibs","IBS"))
cell_order1<-cell_order1%>%mutate(group_major_plus_immune=str_replace(group_major_plus_immune," Memo"," memo")%>%
                                      str_replace("ly Exh","ly exh"))
plot_df<-plot_df%>%
  mutate(group=factor(group,levels=rev(c(cell_order1$group_major_plus_immune,
                                         cell_order$harmonized_major_cell_type[cell_order$type=="non"]))))

traits<-list(A=c("Arthritis","Asthma","IBS","Osteoarthritis"),
              B=c("Abdominal and pelvic pain","Back pain","Dorsalgia","Headache","Pain"),
              C=c("Clear cell ovarian cancer","Endometroid ovarian cancer",
                  "High grade serous ovarian cancer","Hormone-sensitive cancers"),
              D=c("Uterine fibroids","Menopause age"),
              E="Height")
traits<-traits%>%reshape2::melt()
plot_df<-plot_df%>%mutate(trait=factor(trait,levels=traits$value))


sf7<-plot_df%>%
    ggplot(aes(y=group,x=trait,size=prop))+
    geom_point(aes(colour=score))+
    scale_color_gradient2(low="#2166ac",mid="white",high = "#b2182b")+
    geom_point(data=plot_df%>%filter(assoc_mcp<0.05),
              aes(y=group,x=trait,size=prop),col="black",shape=1,show.legend = F)+
    geom_point(data=plot_df%>%filter(assoc_mcp<0.05&hetero_mcp<0.05),
              aes(y=group,x=trait,size=prop),col="black",shape=8,show.legend = F)+
    labs(x="",y="",size="% Signif. Cells",col="scDRS")+
    theme_classic(base_size = 14)+scale_size(range=c(0,8))+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))
ggsave("m_fig6.pdf",device = cairo_pdf,plot=sf7)

```

```{r}
library(FactoMineR)

plot_df<-scdrs%>%
  select(barcode,norm_score,trait)%>%
  pivot_wider(names_from = trait,values_from = norm_score)%>%
  plotcolumn_to_rownames("barcode")

plot_df[is.na(plot_df)]<-0
pcares<-PCA(plot_df)
dimdesc(pcares,axes = 1:2)
```
